### ISSUE TITLE
Error: Unable to find 'elDefs.hpp'

### ISSUE THREAD

**Issue by fernandotorch** [sbrodeur/evert#6]
I think I have installed everything properly following the indications on the readme. However, I get the following error when I try to do the final step `sudo pip2 install .` Any help will be appreciated.

Here is the output from the terminal:
```Installing collected packages: evert
  Found existing installation: evert 1.0
    Can't uninstall 'evert'. No files were found to uninstall.
  Running setup.py install for evert ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-vlkmii4i/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-apftyge7/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    copying evert.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_evert' extension
    swigging evert.i to evert_wrap.cpp
    swig -python -c++ -I../include -o evert_wrap.cpp evert.i
    elVector.i:2: Error: Unable to find 'elDefs.hpp'
    elPolygon.i:2: Error: Unable to find 'elDefs.hpp'
    elAABB.i:2: Error: Unable to find 'elDefs.hpp'
    elBeam.i:2: Error: Unable to find 'elDefs.hpp'
    elTimer.i:2: Error: Unable to find 'elDefs.hpp'
    elBSP.i:2: Error: Unable to find 'elDefs.hpp'
    elGLUT.i:2: Error: Unable to find 'elDefs.hpp'
    elOrientedPoint.i:2: Error: Unable to find 'elDefs.hpp'
    elListener.i:2: Error: Unable to find 'elDefs.hpp'
    elPathSolution.i:2: Error: Unable to find 'elDefs.hpp'
    elRay.i:2: Error: Unable to find 'elDefs.hpp'
    elRoom.i:2: Error: Unable to find 'elDefs.hpp'
    elSource.i:2: Error: Unable to find 'elDefs.hpp'
    elViewer.i:2: Error: Unable to find 'elDefs.hpp'
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
  Can't roll back evert; was not uninstalled
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-vlkmii4i/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-apftyge7/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-vlkmii4i/```

**Comment by sbrodeur** [comment]
The file _elDefs.hpp_ should be present in your local copy:
https://github.com/sbrodeur/evert/blob/master/include/elDefs.hpp

Are you using Python 2 or Python 3?
This is because you mentioned using _pip2_, but I see Python 3 executable is used when compiling EVERT.

Also, which version of SWIG are you using?
I happened to use SWIG 2.x at the beginning, and found out that SWIG 3.x add better support (e.g. keyword arguments in wrapped functions).

**Comment by fernandotorch** [comment]
Thanks so much for the quick response.
You are right in everything, elDefs.hpp is there and I am using python3. I have another conda environment with python2 that I am using and I get the same error message. 

For swig I use SWIG 3.0.12.

I tried to do `sudo pip2 install -e .` and it installed correctly. Could run sygin.room  but unfortunately get an error with cube.py and room.py samples. It seems that I am still doing something incorrectly: 
`Traceback (most recent call last):
  File "cube.py", line 34, in <module>
    from evert import Room, Source, Listener, Vector3, Matrix3, Polygon, PathSolution, Viewer
ImportError: No module named evert`

The behaviour of room.py is the same as for cube.py

**Comment by sbrodeur** [comment]
Here is how I got it working with Conda and Python 3:

```
# Create Conda environment with Python 3
conda create -n evert pip python=3.6
source activate evert
conda install -c anaconda autoconf automake libtool make glib pkg-config swig 
conda install -c anaconda freeglut mesa  mesa-libgl-cos6-x86_64 mesa-libgl-devel-cos6-x86_64

# Download and compile Python extension
git clone https://github.com/sbrodeur/evert.git
cd evert/python
python setup.py install

cd samples
python viewer.py
```

I guess it should work fine with Python 2 as well:
```
# Python 2
conda create -n evert pip python=2.7
source activate evert
conda install -c anaconda autoconf automake libtool make glib pkg-config swig 
conda install -c anaconda freeglut mesa  mesa-libgl-cos6-x86_64 mesa-libgl-devel-cos6-x86_64

# Download and compile Python extension
git clone https://github.com/sbrodeur/evert.git
cd evert/python
python2 setup.py install

cd samples
python2 room.py
```
I'm not sure all sample scripts actually support Python 3.

NOTE: I find that using pip to install custom packages usually leads to weird errors I do not get by using the  _python setup.py install_ .

**Comment by fernandotorch** [comment]
After installing the packages as you said everything works like a charm up to the viewer. The examples room.py and cube.py raise for me an exception, but it seems to have nothing to do with the installation. 

```python cube.py
total polygons: 6
nodes: 5, max depth: 3
list size: 104 bytes (0.00 Mb)
Room maximum length:  1000.0
Room center: x=500.000000, y=500.000000, z=500.000000
Number of elements:  6
Number of convex elements:  6
Number of sources:  1
Number of listeners:  2
-----------------------------------
From source Src1 to listener Lst1
-----------------------------------
building beam tree.. 100.00 % (8251)
paths: 8251 (proc 8256 = 100.00 %, tested 854, valid 780)
Number of paths calculated:  780
Traceback (most recent call last):
  File "cube.py", line 128, in <module>
    main()
  File "cube.py", line 118, in main
    if pathLength < minPathLength or minPathLength is None:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
```


The room.py script also raises the same exception. I am going to try the same thing in python2 just to check if it works and will update this message accordingly. 

Thanks again! From my side I would consider this solved.

Edit: On python 2.7 I could install all packages but failed to install evert using setup.py due to an error related to the compiler (gcc). I won't pursue this further for now but this might be a path that I would take to solve it: 
https://stackoverflow.com/questions/11094718/error-command-gcc-failed-with-exit-status-1-while-installing-eventlet/45771286 
https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory

@sbrodeur: I found the bug in cube.py and room.py has the same. Just changing this solves the problem:
line 118 should be changed from:
`if pathLength < minPathLength or minPathLength is None:` to `if minPathLength is None or pathLength < minPathLength:`, otherwise if the minPathLength is None the comparison raises an exception.
